language: java
nafter_success:
- mvn deploy
before_install:
- openssl aes-256-cbc -K $encrypted_347417494330_key -iv $encrypted_347417494330_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
